namespace Products.Models
{
    /// <summary>
    /// Data transfer object representing a product
    /// </summary>
    /// <remarks>
    /// This DTO is used for returning product data to clients
    /// Generated by Copilot
    /// </remarks>
    public class ProductDto
    {
        /// <summary>
        /// The unique identifier of the product
        /// </summary>
        /// <example>1</example>
        public int Id { get; set; }
        
        /// <summary>
        /// The name of the product
        /// </summary>
        /// <example>Gaming Laptop</example>
        public required string Name { get; set; }
        
        /// <summary>
        /// The price of the product in the default currency
        /// </summary>
        /// <example>999.99</example>
        public decimal Price { get; set; }
    }

    /// <summary>
    /// Data transfer object for creating a new product
    /// </summary>
    /// <remarks>
    /// This DTO is used when adding new products to the system
    /// Generated by Copilot
    /// </remarks>
    public class ProductInsertDto
    {
        /// <summary>
        /// The name of the product to create
        /// </summary>
        /// <example>Gaming Laptop</example>
        public required string Name { get; set; }
        
        /// <summary>
        /// The price of the product in the default currency
        /// </summary>
        /// <example>999.99</example>
        public decimal Price { get; set; }
    }
}
