using AutoMapper;
using Products.Domain.Entities;
using Products.Models;

namespace Products.Mappings
{
    /// <summary>
    /// AutoMapper profile for mapping between Product entities and DTOs
    /// </summary>
    /// <remarks>
    /// Generated by Copilot
    /// </remarks>
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // Map from Product entity to ProductDto
            CreateMap<Product, ProductDto>();
            
            // Map from ProductInsertDto to Product entity
            CreateMap<ProductInsertDto, Product>();
            
            // Map from ProductDto to Product entity
            CreateMap<ProductDto, Product>();
        }
    }
}