@echo off
REM Generated by Copilot
REM Run tests with coverage and generate HTML report in Products.Tests\TestResults

cd /d %~dp0

REM Run tests with coverage (XPlat Code Coverage)
dotnet test --collect:"XPlat Code Coverage"

REM Find the latest coverage.cobertura.xml file
for /f "delims=" %%i in ('dir /b /s /o-d TestResults\\coverage.cobertura.xml') do (
    set "COVERAGE_FILE=%%i"
    goto :found
)
echo Coverage file not found!
pause
exit /b 1

:found
REM Generate HTML report using ReportGenerator
dotnet tool install -g dotnet-reportgenerator-globaltool --ignore-failed-sources
set PATH=%PATH%;%USERPROFILE%\.dotnet\tools
reportgenerator -reports:"%COVERAGE_FILE%" -targetdir:TestResults\coverage-report -reporttypes:Html

echo Coverage report generated at Products.Tests\TestResults\coverage-report\index.html
pause
